[workspace]
# It's its own workspace - hide it from the root workspace

[package]
name = "radix-cli"
version = "1.2.0-dev"
edition = "2021"
license = "Radix License 1.0"
description = "A collection of CLIs for developing, building and testing Scrypto code."
readme = "README.md"

[dependencies]
sbor = { path = "../sbor" }
radix-engine = { path = "../radix-engine" }
radix-substate-store-interface = { path = "../radix-substate-store-interface" }
radix-substate-store-impls = { path = "../radix-substate-store-impls", features = ["rocksdb"] }
radix-substate-store-queries = { path = "../radix-substate-store-queries" }
radix-common = { path = "../radix-common" }
radix-engine-interface = { path = "../radix-engine-interface" }
radix-engine-profiling = { path = "../radix-engine-profiling", features = ["ram_metrics"] }
radix-blueprint-schema-init = { path = "../radix-blueprint-schema-init" }
radix-transactions = { path = "../radix-transactions" }

flate2 = { version = "1.0.27" }
tar = { version = "0.4.40" }
rocksdb = { version = "0.21.0" }
radix-rust = { path = "../radix-rust" }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.81" }
clap = { version = "3.1.17", features = ["derive", "cargo"] }
dirs = { version = "4.0.0" }
colored = { version = "2.0.0" }
hex = { version = "0.4.3" }
cargo_toml = { version = "0.11.5" }
rand = { version = "0.8.5" }
regex = { version = "1.5.5" }
temp-env = { version = "0.2.0" }
wasm-opt = { version = "0.114.1" }
syn = { git = "https://github.com/dtolnay/syn.git", tag = "1.0.93", features = ["full", "extra-traits"] }
quote = { version = "1.0.18" }
proc-macro2 = { version = "1.0.38" }
heck = "0.4.1"
tempfile = "3.8.0"
flume = { version = "0.11.0" }
walkdir = "2.3.3"

[[bin]]
name = "resim"
path = "src/bin/resim.rs"
bench = false

[[bin]]
name = "scrypto"
path = "src/bin/scrypto.rs"
bench = false

[[bin]]
name = "rtmc"
path = "src/bin/rtmc.rs"
bench = false

[[bin]]
name = "rtmd"
path = "src/bin/rtmd.rs"
bench = false

[[bin]]
name = "scrypto-bindgen"
path = "src/bin/scrypto_bindgen.rs"
bench = false

[[bin]]
name = "replay"
path = "src/bin/replay.rs"
bench = false

[lib]
doctest = false
bench = false

[profile.bench]
debug = true