[package]
name = "radiswap"
version = "1.2.0-dev"
edition = "2021"
license = "Radix License 1.0"

[dependencies]
sbor = { path = "../../../sbor" }
scrypto = { path = "../../../scrypto" }

[dev-dependencies]
scrypto-test = { path = "../../../scrypto-test" }

[features]
default = []

[lib]
doctest = false
crate-type = ["cdylib", "lib"]