[package]
name = "sbor-derive-common"
version = "1.2.0-dev"
edition = "2021"
license = "Radix License 1.0"
description = "A library for implementing SBOR derives."

[dependencies]
proc-macro2 = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"] }
quote = { workspace = true }
const-sha1 = { workspace = true } # Chosen because of its small size and 0 transitive dependencies
itertools = { workspace = true }

[features]
trace = []

[lib]
doctest = false
bench = false
