[package]
name = "scrypto-bindgen"
version = "1.3.0-dev"
edition = "2021"
description = "A library for generating Scrypto bindings."
readme = "README.md"
license-file = "../LICENSE"

[dependencies]
radix-engine-interface = { workspace = true }
radix-common = { workspace = true }
radix-engine = { workspace = true }
radix-rust = { workspace = true }
serde_json = { workspace = true }
wasm-opt = { workspace = true }
cargo_toml = { workspace = true }
radix-blueprint-schema-init = { workspace = true }
proc-macro2 = { version = "1.0.38" }
quote = { version = "1.0.18" }
syn = { version = "1.0.93", features = ["full", "extra-traits"] }

[dev-dependencies]
tempdir = "0.3.7"

[lib]
doctest = false
bench = false

[features]
default = ["std"]
std = ["serde_json/std", "radix-engine-interface/std", "radix-common/std", "radix-engine/std", "radix-engine/moka", "radix-rust/std"]
alloc = ["serde_json/alloc", "radix-engine-interface/alloc", "radix-common/alloc", "radix-engine/alloc", "radix-engine/lru", "radix-rust/alloc"]
