[package]
name = "scrypto-bindgen"
version = "1.4.0-dev"
edition = "2021"
description = "A library for generating Scrypto bindings."
readme = "README.md"
license-file = "../LICENSE"

[dependencies]
radix-blueprint-schema-init = { workspace = true }
radix-common = { workspace = true }
radix-engine = { workspace = true }
radix-engine-interface = { workspace = true }
radix-rust = { workspace = true }

serde_json = { workspace = true }
wasm-opt = { workspace = true }
cargo_toml = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lib]
bench = false

[features]
default = ["std"]
std = [
    "serde_json/std",
    "radix-blueprint-schema-init/std",
    "radix-engine-interface/std",
    "radix-common/std",
    "radix-engine/std",
    "radix-engine/moka",
    "radix-rust/std"
]
alloc = [
    "serde_json/alloc",
    "radix-blueprint-schema-init/alloc",
    "radix-engine-interface/alloc",
    "radix-common/alloc",
    "radix-engine/alloc",
    "radix-engine/lru",
    "radix-rust/alloc"
]
