[package]
name = "wasm-benchmarks-lib"
version = "1.2.0-dev"
edition = "2021"
license = "Radix License 1.0"

[lib]
doctest = false
crate-type = ["cdylib", "rlib"]
# Ref: https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[dependencies]
radix-common = { path = "../../radix-common", default-features = false }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["radix-common/std"]
alloc = ["radix-common/alloc"]
