[package]
name = "substate-store-impls"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
sbor = { workspace = true }
utils = { workspace = true }
radix-engine-common = { workspace = true }
substate-store-interface = { workspace = true }
rocksdb = { workspace = true, optional = true }
itertools = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
tempfile = "3.8.0"

[features]
default = ["std"]
std = ["hex/std", "sbor/std", "utils/std", "radix-engine-common/std", "substate-store-interface/std", "itertools/use_std"]
alloc = ["hex/alloc", "sbor/alloc", "utils/alloc", "radix-engine-common/alloc", "substate-store-interface/alloc", "itertools/use_alloc"]

rocksdb = ["dep:rocksdb"]

# Ref: https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
doctest = false
bench = false
