[package]
name = "faucet"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
sbor = { path = "../../../../sbor" }
scrypto = { path = "../../../../scrypto" }

[dev-dependencies]
scrypto-test = { path = "../../../../scrypto-test" }

[lib]
doctest = false
crate-type = ["cdylib", "lib"]