[package]
name = "test_environment"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
sbor = { path = "../../../../sbor" }
scrypto = { path = "../../../../scrypto" }

[lib]
doctest = false
crate-type = ["cdylib", "lib"]