[package]
name = "scrypto-compiler"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
radix-engine-interface = { path = "../radix-engine-interface", default-features = false }
radix-engine = { path = "../radix-engine", default-features = false }
utils = { path = "../utils", default-features = false }
serde_json = { version = "1.0.81", default-features = false }
wasm-opt = { version = "0.114.1" }
cargo_toml = { version = "0.19.2" }

[dev-dependencies]
tempdir = "0.3.7"

[lib]
doctest = false
bench = false

[features]
default = ["std"]
std = ["serde_json/std", "radix-engine-interface/std", "radix-engine/std", "radix-engine/moka", "utils/std"]
alloc = ["serde_json/alloc", "radix-engine-interface/alloc", "radix-engine/alloc", "radix-engine/lru", "utils/alloc"]
