[package]
name = "oracle_proxy_with_owned"
version = "1.0.0"
edition = "2021"

[dependencies]
scrypto = { path = "../../../../../scrypto" }

[features]
default = []
test = []

[lib]
crate-type = ["cdylib", "lib"]
