[package]
name = "transaction"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
sbor = { workspace = true }
radix-rust = { workspace = true }
radix-engine-interface = { workspace = true }
radix-engine-common = { workspace = true, features = ["secp256k1_sign_and_validate"]}
hex = { workspace = true }
serde = { workspace = true, optional = true }
lazy_static = { workspace = true }
strum = { workspace = true }
bech32 = { workspace = true }

[dev-dependencies]
scrypto = { path = "../scrypto" }
scrypto-derive = { path = "../scrypto-derive" }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["sbor/std", "radix-rust/std", "radix-engine-interface/std", "radix-engine-common/std", "hex/std"]
alloc = ["sbor/alloc", "radix-rust/alloc", "radix-engine-interface/alloc", "radix-engine-common/alloc", "hex/alloc", "lazy_static/spin_no_std"]
serde = ["serde/derive"]

dump_manifest_to_file = []

# This flag is set by fuzz-tests framework
radix_engine_fuzzing = [
    "sbor/radix_engine_fuzzing",
    "radix-rust/radix_engine_fuzzing",
    "radix-engine-interface/radix_engine_fuzzing",
    "radix-engine-common/radix_engine_fuzzing",
]

[lib]
doctest = false
bench = false
