[package]
name = "radix-rust"
version = "1.2.0-dev"
edition = "2021"

[dependencies]
serde = { workspace = true, optional = true }
hashbrown = { workspace = true, optional = true }
indexmap = { workspace = true }

[features]
default = ["std"]
std = ["indexmap/std"]
alloc = ["hashbrown"]
serde = ["serde/derive", "indexmap/serde"]
# This flag is set by fuzz-tests framework and it enables StubHasher (instead of RandomHasher) for
# Map and Set structs to prevent non-determinism when fuzzing.
radix_engine_fuzzing = ["indexmap/arbitrary"]

[lib]
doctest = false
bench = false
