[package]
name = "sbor-derive"
version = "1.2.0-dev"
edition = "2021"

[lib]
doctest = false
proc-macro = true
bench = false

[dependencies]
proc-macro2 = { workspace = true }
sbor-derive-common = { workspace = true }

[features]
trace = ["sbor-derive-common/trace"]
