name: Publish scrypto-dev-container image

on:
  workflow_dispatch:
    inputs:
      image-label:
        description: "Docker image label to be published"

permissions:
  packages: write
  pull-requests: write
  id-token: write
  contents: read

jobs:
  build-amd:
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-16-cores-selfhosted
      environment: "release"
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "scrypto-dev-container"
      tag: ${{ inputs.image-label }}
      context: "."
      dockerfile: "Dockerfile"
      target: "scrypto-dev-container"
      platforms: "linux/amd64"
      provenance: "false"
      scan_image: true
      snyk_target_ref: ${{ github.ref_name }}
      enable_dockerhub: true
    secrets:
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}
