name: Publish cargo crates

on:
  release:
    types: [published]

permissions:
  packages: write
  pull-requests: write
  id-token: write
  contents: read

jobs:
  publish-crates:
    runs-on: ubuntu-latest
    steps:
    - uses: RDXWorks-actions/checkout@main
    - uses: radixdlt/iac-resuable-artifacts/fetch-secrets@v0.8.0
      with:
        role_name: "arn:aws:iam::308190735829:role/gh-common-secret-access"
        app_name: "radixdlt-scrypto"
        step_name: "publish crate"
        secret_prefix: "CRATES"
        secret_name: "arn:aws:secretsmanager:eu-west-2:308190735829:secret:github-actions/radixdlt/radixdlt-scrypto/crates-token"
        parse_json: true
    - name: Publish crates
      run: |
        ./publish-cargo-crates.sh
      env:
        CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
      continue-on-error: true


  

